#Each new term in the Fibonacci sequence is generated by adding the previous two
#terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do
#not exceed four million, find the sum of the even-valued terms.

# First make Fibonacci Counter

fib0 = 1
fib1 = 2
print(fib0)
print(fib1)
summer = 0
fall = 0
while summer < 4000000:
    summer = fib0 + fib1
    fib0 = fib1
    fib1 = summer
    #print(fib1)
    if summer % 2 == 0:
        fall += summer

fall += 2
print(fall)




